yt-dlp:
  loader-absolute-path: ${LOADER_ABSOLUTE_PATH}
  loader-file-name: ${LOADER_FILE_NAME}
  audio-format: ${AUDIO_FORMAT}
  target-absolute-path: ${TARGET_ABSOLUTE_PATH}
  target-url: ${TARGET_URL}

y2rss-api:
  url: ${Y2RSS_API_URL}
  username: ${Y2RSS_API_USERNAME}
  password: ${Y2RSS_API_PASSWORD}

scheduler:
  core-pool-size: ${CORE_POOL_SIZE}
  max-pool-size: ${MAX_POOL_SIZE}
  queue-capacity: ${QUEUE_CAPACITY}
  scheduled-delay-ms: ${SCHEDULED_DELAY_MS}

logging:
  level:
    root: ${LOGIN_LEVEL_ROOT}
    farm.giggle: ${LOGIN_LEVEL_APPLICATION_MAIN_PACKET}

minio:
  access-key: ${MINIO_ACCESS_KEY}
  secret-key: ${MINIO_SECRET_KEY}
  endpoint: ${MINIO_ENDPOINT}
  bucket-name: ${MINIO_BUCKET_NAME}